name: Release
on:
  push:
    tags:
      - "*"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Initialize environment
        run: just init-venv

      - name: Bump version
        run: just bump-version

      - name: Check if no diffs
        run: just assert-has-no-diffs

      - name: Build
        run: just build

      - name: Create PyPi configuration file
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          touch ~/.pypirc
          echo "[pypi]" >> ~/.pypirc
          echo "username = __token__" >> ~/.pypirc
          echo "password = $PYPI_TOKEN" >> ~/.pypirc

      - name: Upload
        run: just upload
